version: "3"

services:
    web:
        build: .
        volumes:
            - ./:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - message-broker
        restart: on-failure

    celery-worker:
        build: .
        command: celery -A takehomegai worker -l info
        volumes:
            - ./:/usr/src/app
        depends_on:
            - message-broker
        restart: on-failure
    
    message-broker:
        image: rabbitmq:latest
        ports:
            - "5672:5672"
        restart: on-failure
    # TODO postgresql